export enum HomeScreenActions {
    DISPLAYED_POSTS_REQUESTED = "DISPLAYED_POSTS_REQUESTED",
    DISPLAYED_POSTS_REQUEST_SUCCEEDED = "DISPLAYED_POSTS_REQUEST_SUCCEEDED",
    DISPLAYED_POSTS_REQUEST_FAILED = "DISPLAYED_POSTS_REQUEST_SUCCEEDED",
}