export enum Colors {
    BACKGROUND_GRAY = "#323238",
    POST_LISTING_GRAY = "#3F3F45",
    ACTION_BAR_PURPLE = "#4F395E",
    PURPLE = "#CA91F2",
    WHITE = "#FFFFFF",
    BLACK = "#000000",
    OVERLAY_GRAY = "#00000090",
    OVERLAY_BLACK = "#00000060",
    NSFW_RED = "#A63039",
}

export const BACKGROUND_COLOR = Colors.BACKGROUND_GRAY;
export const POST_LISTING_COLOR = Colors.POST_LISTING_GRAY;
export const ACTION_BAR_COLOR = Colors.ACTION_BAR_PURPLE;
export const LINK_COLOR = Colors.PURPLE;